[project]
name = "python-training"
version = "0.1.0"
description = "Your project"
authors = [{ name = "Uday" }]
requires-python = ">=3.11"

dependencies = [
    "fastapi",
    "uvicorn",
    "requests",
    "pandas",
    "numpy",
    "pyspark",
    "duckdb",
    "polars",
    "ray",
    "PyYAML",
    "scikit-learn",
    "transformers",
    "sentence-transformers"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "black[jupyter]",
    "ruff",
    "mypy"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
